baseurl = "/"
languageCode = "en-us"
title = "StatusKit"

[permalinks]
  incidents = "/incidents/:year/:month/:day/:slug/"

[params]
  defaultLogo = "https://www.netlify.com/img/press/logos/logomark.svg"
  faviconsPath = "/images/favicon/"
